services:
  notification:
    container_name: notification
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: unless-stopped
    volumes:
      - ../../ELK-stack/secrets/certs:/app/certs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  default:
    name: bukiteasy
    external: true