services:
  notification:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
